### ISSUE TITLE
DracoPy version issue

### ISSUE THREAD

**Issue by zhangfanmark** [haehn/TRAKO#1]
Follow the instructions, I started the installation from a clean minaconda env and found DracoPy was not installed. I did:

pip install DracoPy

After that I tried the examples, but it failed with the following error. Maybe something wrong with the version of DracoPy?

![image](https://user-images.githubusercontent.com/7855446/68863769-fce9fc80-06bd-11ea-92c8-03bca91feb77.png)

**Comment by haehn** [comment]
Yes - we use a different fork of DracoPy. It will not work with the pip version.
The instructions include these steps to set up the custom DracoPy.

# initialize DracoPy submodule
git submodule init
git submodule update

cd externals/DracoPy
# initialize Draco submodule
git submodule init
git submodule update
python setup.py install

**Comment by zhangfanmark** [comment]
I think I did the above steps but it said can not find DracoPy. Then, I installed via pip.

Now, I uninstalled the pip dracopy, and rerun the above steps. It says"ModuleNotFoundError: No module named 'DracoPy'"

**Comment by haehn** [comment]
Hmm not sure whats happening. I tried on multiple machines from scratch. Are you using linux? What happens when you run python setup.py install in externals/DracoPy - can you please paste the output?

**Comment by haehn** [comment]
@zhangfanmark I just tried again on a completely new machine (Chromebook running linux) and it works without a problem using the steps

**Comment by haehn** [comment]
and I tried one more time, fresh computer, fresh install.. worked again (ubuntu 18.04). I will now try to create a python setup.py to make things easier

**Comment by zhangfanmark** [comment]
There might be something wrong with my setting. Now my python env has been totally messed up. I have to reinstall everything and give a try later. I will send you a link later to a read whole brain tract dataset later via email.

**Comment by haehn** [comment]
Sorry to hear about the mess, `pip install trako` should make things easier now

**Comment by haehn** [comment]
closing this!
