### ISSUE TITLE
No module named 'optuna'

### ISSUE THREAD

**Issue by tashrifbillah** [haehn/TRAKO#4]
> trakofy -h

```bash
Traceback (most recent call last):
  File "/tmp/miniconda3-trako/bin/trakofy", line 2, in <module>
    import trako as TKO
  File "/tmp/miniconda3-trako/lib/python3.7/site-packages/trako/__init__.py", line 2, in <module>
    from .tuner import Tuner
  File "/tmp/miniconda3-trako/lib/python3.7/site-packages/trako/tuner.py", line 3, in <module>
    import optuna
ModuleNotFoundError: No module named 'optuna'
```

Same error occurs with the other two executables noted in README.

**Comment by pieper** [comment]
Did you try pip installing https://pypi.org/project/optuna/ ?

Probably need to fix the requirements.txt file.

**Comment by tashrifbillah** [comment]
@haehn , do we have a preference for optuna version? In the separate conda environment, I `pip install optuna` and the following came with `optuna-1.3.0`:

> Installing collected packages: sqlalchemy, python-editor, MarkupSafe, Mako, alembic, pbr, stevedore, pyperclip, cmd2, PyYAML, cliff, cmaes, colorlog, joblib, scipy, tqdm, optuna
Successfully installed Mako-1.1.2 MarkupSafe-1.1.1 PyYAML-5.3.1 alembic-1.4.2 cliff-3.1.0 cmaes-0.4.0 cmd2-0.8.9 colorlog-4.1.0 joblib-0.14.1 optuna-1.3.0 pbr-5.4.5 pyperclip-1.8.0 python-editor-1.0.4 scipy-1.4.1 sqlalchemy-1.3.16 stevedore-1.32.0 tqdm-4.45.0

**Comment by haehn** [comment]
Good catch! We can actually remove that.
